# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/geant4/Geant4/itrs_examples/Linac_NovalisTx_PhspMT_Geant4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/geant4/Geant4/itrs_examples/Linac_NovalisTx_PhspMT_Geant4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geant4/Geant4/itrs_examples/Linac_NovalisTx_PhspMT_Geant4/CMakeFiles /home/geant4/Geant4/itrs_examples/Linac_NovalisTx_PhspMT_Geant4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geant4/Geant4/itrs_examples/Linac_NovalisTx_PhspMT_Geant4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExitAndInvivoDosimetry

# Build rule for target.
ExitAndInvivoDosimetry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExitAndInvivoDosimetry
.PHONY : ExitAndInvivoDosimetry

# fast build rule for target.
ExitAndInvivoDosimetry/fast:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/build
.PHONY : ExitAndInvivoDosimetry/fast

ExitAndInvivoDosimetry.o: ExitAndInvivoDosimetry.cc.o

.PHONY : ExitAndInvivoDosimetry.o

# target to build an object file
ExitAndInvivoDosimetry.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/ExitAndInvivoDosimetry.cc.o
.PHONY : ExitAndInvivoDosimetry.cc.o

ExitAndInvivoDosimetry.i: ExitAndInvivoDosimetry.cc.i

.PHONY : ExitAndInvivoDosimetry.i

# target to preprocess a source file
ExitAndInvivoDosimetry.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/ExitAndInvivoDosimetry.cc.i
.PHONY : ExitAndInvivoDosimetry.cc.i

ExitAndInvivoDosimetry.s: ExitAndInvivoDosimetry.cc.s

.PHONY : ExitAndInvivoDosimetry.s

# target to generate assembly for a file
ExitAndInvivoDosimetry.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/ExitAndInvivoDosimetry.cc.s
.PHONY : ExitAndInvivoDosimetry.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o

.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i

.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s

.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/FileReader.o: src/FileReader.cc.o

.PHONY : src/FileReader.o

# target to build an object file
src/FileReader.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/FileReader.cc.o
.PHONY : src/FileReader.cc.o

src/FileReader.i: src/FileReader.cc.i

.PHONY : src/FileReader.i

# target to preprocess a source file
src/FileReader.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/FileReader.cc.i
.PHONY : src/FileReader.cc.i

src/FileReader.s: src/FileReader.cc.s

.PHONY : src/FileReader.s

# target to generate assembly for a file
src/FileReader.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/FileReader.cc.s
.PHONY : src/FileReader.cc.s

src/MyRun.o: src/MyRun.cc.o

.PHONY : src/MyRun.o

# target to build an object file
src/MyRun.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/MyRun.cc.o
.PHONY : src/MyRun.cc.o

src/MyRun.i: src/MyRun.cc.i

.PHONY : src/MyRun.i

# target to preprocess a source file
src/MyRun.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/MyRun.cc.i
.PHONY : src/MyRun.cc.i

src/MyRun.s: src/MyRun.cc.s

.PHONY : src/MyRun.s

# target to generate assembly for a file
src/MyRun.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/MyRun.cc.s
.PHONY : src/MyRun.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PolygonDataImport.o: src/PolygonDataImport.cc.o

.PHONY : src/PolygonDataImport.o

# target to build an object file
src/PolygonDataImport.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PolygonDataImport.cc.o
.PHONY : src/PolygonDataImport.cc.o

src/PolygonDataImport.i: src/PolygonDataImport.cc.i

.PHONY : src/PolygonDataImport.i

# target to preprocess a source file
src/PolygonDataImport.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PolygonDataImport.cc.i
.PHONY : src/PolygonDataImport.cc.i

src/PolygonDataImport.s: src/PolygonDataImport.cc.s

.PHONY : src/PolygonDataImport.s

# target to generate assembly for a file
src/PolygonDataImport.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PolygonDataImport.cc.s
.PHONY : src/PolygonDataImport.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SensitiveDetector.o: src/SensitiveDetector.cc.o

.PHONY : src/SensitiveDetector.o

# target to build an object file
src/SensitiveDetector.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/SensitiveDetector.cc.o
.PHONY : src/SensitiveDetector.cc.o

src/SensitiveDetector.i: src/SensitiveDetector.cc.i

.PHONY : src/SensitiveDetector.i

# target to preprocess a source file
src/SensitiveDetector.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/SensitiveDetector.cc.i
.PHONY : src/SensitiveDetector.cc.i

src/SensitiveDetector.s: src/SensitiveDetector.cc.s

.PHONY : src/SensitiveDetector.s

# target to generate assembly for a file
src/SensitiveDetector.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/SensitiveDetector.cc.s
.PHONY : src/SensitiveDetector.cc.s

src/StackingAction.o: src/StackingAction.cc.o

.PHONY : src/StackingAction.o

# target to build an object file
src/StackingAction.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/StackingAction.cc.o
.PHONY : src/StackingAction.cc.o

src/StackingAction.i: src/StackingAction.cc.i

.PHONY : src/StackingAction.i

# target to preprocess a source file
src/StackingAction.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/StackingAction.cc.i
.PHONY : src/StackingAction.cc.i

src/StackingAction.s: src/StackingAction.cc.s

.PHONY : src/StackingAction.s

# target to generate assembly for a file
src/StackingAction.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/StackingAction.cc.s
.PHONY : src/StackingAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/TrackingAction.o: src/TrackingAction.cc.o

.PHONY : src/TrackingAction.o

# target to build an object file
src/TrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/TrackingAction.cc.o
.PHONY : src/TrackingAction.cc.o

src/TrackingAction.i: src/TrackingAction.cc.i

.PHONY : src/TrackingAction.i

# target to preprocess a source file
src/TrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/TrackingAction.cc.i
.PHONY : src/TrackingAction.cc.i

src/TrackingAction.s: src/TrackingAction.cc.s

.PHONY : src/TrackingAction.s

# target to generate assembly for a file
src/TrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/TrackingAction.cc.s
.PHONY : src/TrackingAction.cc.s

src/_SensitiveDetectorInPhantom.o: src/_SensitiveDetectorInPhantom.cc.o

.PHONY : src/_SensitiveDetectorInPhantom.o

# target to build an object file
src/_SensitiveDetectorInPhantom.cc.o:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/_SensitiveDetectorInPhantom.cc.o
.PHONY : src/_SensitiveDetectorInPhantom.cc.o

src/_SensitiveDetectorInPhantom.i: src/_SensitiveDetectorInPhantom.cc.i

.PHONY : src/_SensitiveDetectorInPhantom.i

# target to preprocess a source file
src/_SensitiveDetectorInPhantom.cc.i:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/_SensitiveDetectorInPhantom.cc.i
.PHONY : src/_SensitiveDetectorInPhantom.cc.i

src/_SensitiveDetectorInPhantom.s: src/_SensitiveDetectorInPhantom.cc.s

.PHONY : src/_SensitiveDetectorInPhantom.s

# target to generate assembly for a file
src/_SensitiveDetectorInPhantom.cc.s:
	$(MAKE) -f CMakeFiles/ExitAndInvivoDosimetry.dir/build.make CMakeFiles/ExitAndInvivoDosimetry.dir/src/_SensitiveDetectorInPhantom.cc.s
.PHONY : src/_SensitiveDetectorInPhantom.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... ExitAndInvivoDosimetry"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... ExitAndInvivoDosimetry.o"
	@echo "... ExitAndInvivoDosimetry.i"
	@echo "... ExitAndInvivoDosimetry.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/FileReader.o"
	@echo "... src/FileReader.i"
	@echo "... src/FileReader.s"
	@echo "... src/MyRun.o"
	@echo "... src/MyRun.i"
	@echo "... src/MyRun.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PolygonDataImport.o"
	@echo "... src/PolygonDataImport.i"
	@echo "... src/PolygonDataImport.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SensitiveDetector.o"
	@echo "... src/SensitiveDetector.i"
	@echo "... src/SensitiveDetector.s"
	@echo "... src/StackingAction.o"
	@echo "... src/StackingAction.i"
	@echo "... src/StackingAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/TrackingAction.o"
	@echo "... src/TrackingAction.i"
	@echo "... src/TrackingAction.s"
	@echo "... src/_SensitiveDetectorInPhantom.o"
	@echo "... src/_SensitiveDetectorInPhantom.i"
	@echo "... src/_SensitiveDetectorInPhantom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

